jobs:
  include:
    - stage: test
      dist: xenial   # required for Python >= 3.7
      language: python
      python:
        - "3.7"
      env:
        - DJANGO_SETTINGS_MODULE='riclibre.settings.travis' MOZ_HEADLESS=1
        - DJANGO_SECRET_KEY=fake_test_key
        - DEBUG=True
        - BROKER_URL=redis://localhost
        - DESACTIVATE_RECAPTCHA=True
      addons:
        postgresql: "9.4"
        firefox: latest
        apt:
          packages:
            - tesseract-ocr
            - libtesseract-dev
      services:
        - postgresql
      before_install:
        - wget https://github.com/mozilla/geckodriver/releases/download/v0.22.0/geckodriver-v0.22.0-linux64.tar.gz
        - mkdir geckodriver
        - tar -xzf geckodriver-v0.22.0-linux64.tar.gz -C geckodriver
        - export PATH=$PATH:$PWD/geckodriver
        - geckodriver --version
        - export MOZ_HEADLESS=1
      install:
        - pip install -r requirements.txt
      before_script:
        - echo 'Europe/Paris' | sudo tee /etc/timezone
        - sudo dpkg-reconfigure --frontend noninteractive tzdata
        - sudo ntpdate ntp.ubuntu.com
        - psql -c 'create database travis_ci_test;' -U postgres
      script:
        - python manage.py migrate
        - python manage.py test
    - stage: deploy
      if: branch = master
      language: minimal
      before_script:
        - openssl aes-256-cbc -K $encrypted_58d87a1c206d_key -iv $encrypted_58d87a1c206d_iv -in deploy/deploy_key.enc -out deploy/deploy_key -d
        - chmod +x deploy/deploy.sh
      script: deploy/deploy.sh